title: SwiftScale Migrator
description: Language-agnostic SQL migration engine built in c#
theme: just-the-docs

url: "https://onas1.github.io"
baseurl: "/swift-migrator"

markdown: kramdown

just_the_docs:
  search_enabled: true
  aux_links:
    "View on GitHub":
      url: "https://github.com/<your-github-username>/swift-migrator"





