
title: Swift Migrator
description: Language-agnostic SQL migration engine built in C#.
theme: just-the-docs

url: https://onas1.github.io/swift-migrator
baseurl: ""

just_the_docs:
  search_enabled: true
  aux_links:
    "View on GitHub":
      - "https://onas1.github.io/swift-migrator"